In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('hindi_claims(1).csv')

In [4]:
df.head()

,query,query_lang,claim_text,claimant,claim_date,publisher_name,publisher_site,review_title,review_url,review_date,rating,language
0,जन धन योजना,NaN,बीजेपी सरकार ने शुरू की लोगों को 5000 रुपए ऑनल...,Facebook,2026-02-09T14:23:58Z,The Quint,thequint.com,केंद्र सरकार की योजना में ₹5000 मिलने का दावा ...,https://www.thequint.com/hindi/webqoof/fact-ch...,2026-02-09T14:23:58Z,False,hi
1,जन धन योजना,NaN,जन धन योजना के तहत प्रधानमंत्री नरेंद्र की तरफ...,"Facebook,Social Media,Twitter",2025-09-17T01:44:18Z,The Quint,thequint.com,पीएम मोदी की तरफ से 3000 रुपए गिफ्ट का दावा कर...,https://www.thequint.com/hindi/webqoof/truth-b...,2025-09-17T01:44:18Z,False,hi
2,जन धन योजना,NaN,जन धन योजना के तहत भारत सरकार दे रही है दो हजा...,FB User JAN DHAN YOJNA,2025-06-26T07:54:38Z,विश्वास न्यूज,vishvasnews.com,Fact Check: जन धन योजना के नाम से वायरल हुआ फर...,https://www.vishvasnews.com/financial-fraud/fa...,2025-06-26T07:54:38Z,False,hi
3,जन धन योजना,NaN,भारतीय नागरिक के खाते में ₹3999 मुफ्त,फेसबुक यूजर ‘Inaam jeeto 2’,2024-04-05T07:19:09Z,विश्वास न्यूज,vishvasnews.com,Fact Check : सरकारी योजना के नाम पर मुफ्त पैसे...,https://www.vishvasnews.com/scam/fact-check-vi...,2024-04-05T07:19:09Z,False,hi
4,जन धन योजना,NaN,फेसबुक यूजर ‘Rashmi 7’ ने 21 मार्च 2024 को वाय...,Facebook user ‘Rashmi 7’,2024-03-26T08:18:12Z,विश्वास न्यूज,vishvasnews.com,Fact Check : होली पर प्रधानमंत्री जन धन योजना ...,https://www.vishvasnews.com/scam/fact-check-cl...,2024-03-26T08:18:12Z,False,hi

In [5]:
df.dropna(inplace=True)

In [6]:
df.head()

,query,query_lang,claim_text,claimant,claim_date,publisher_name,publisher_site,review_title,review_url,review_date,rating,language
8628,परीक्षा,curated,"cbse की 10वीं की परीक्षा रद्द, 12वीं की परीक्ष...",Social Media Users,2023-01-22T12:27:05Z,Boom Live,hindi.boomlive.in,Old video viral with claim of cancellation of ...,https://hindi.boomlive.in/fact-check/cbse-10th...,2023-01-22T12:27:05Z,False,hi
8630,रिजल्ट,curated,चुनाव का परिणाम भांपते हुए पीएम नरेंद्र मोदी स...,Facebook Users,2024-05-18T10:49:17Z,Boom Live,hindi.boomlive.in,अखिलेश यादव का पीएम मोदी से मुलाकात का वायरल व...,https://hindi.boomlive.in/fact-check/akhilesh-...,2024-05-18T10:49:17Z,Misleading,hi
8631,रिजल्ट,curated,पश्चिम बंगाल चुनाव परिणाम के बाद हुई हिंसा में...,सोशल मीडिया यूज़र्स,2016-06-20T00:00:00Z,Alt News,altnews.in,2019 में अमित शाह की रैली में हुई हिंसा की तस्...,https://www.altnews.in/hindi/2019-image-of-cla...,2021-05-04T00:00:00Z,False,hi
8633,यूपीएससी,curated,UPSC परीक्षा पास करने वाली कश्मीरी महिला नादिय...,Social Media,2016-06-20T00:00:00Z,Alt News,altnews.in,UPSC क्लियर करने वाली कश्मीरी महिला नादिया बेग...,https://www.altnews.in/hindi/fake-twitter-acco...,2020-08-08T00:00:00Z,False,hi
8634,RBI,curated,आरबीआई ने ₹500 और ₹1000 के पुराने नोट बदलने का...,Facebook and Instagram user,2025-10-30T08:40:52Z,Boom Live,hindi.boomlive.in,पुराने ₹500 और ₹1000 के नोट बदलने के लिए RBI क...,https://hindi.boomlive.in/fact-check/the-claim...,2025-10-30T08:40:52Z,False,hi